[theme]
primaryColor = "#0A2B24"
backgroundColor = "#F5EFE6"
secondaryBackgroundColor = "#ECE6DB"
textColor = "#08201A"
font = "sans serif"

[server]
address = "127.0.0.1"
headless = true
enableCORS = true
enableXsrfProtection = true
